*! 劳力成本：labour-costs
*! 最低工资：minimum-wages
*! 非农就业数据：non-farm-payrolls
*! 兼职就业数据：part-time-employment
*! 人口：population
*! 生产率：productivity
*! 男性退休年龄：retirement-age-men
*! 女性退休年龄：retirement-age-women
*! 失业人员：unemployed-persons
*! 工资增长率：wage-growth
*! 工资：wages
*! 制造业工资：wages-in-manufacturing
*!######## 价格数据 ###########
*! 居民消费价格指数CPI：consumer-price-index-cpi
*! 核心消费者物价指数：core-consumer-prices
*! 核心通胀率：core-inflation-rate
*! 出口价格：export-prices
*! 进口价格：import-prices
*! 国内生产总值平减指数：gdp-deflator
*! 生产者价格指数：producer-prices
*! 消费物价协调指数：harmonised-consumer-prices
*!######## 金融数据 ###########
*! 银行资产负债表：banks-balance-sheet
*! 央行资产负债表：central-bank-balance-sheet
*! 外汇储备：foreign-exchange-reserves
*! 私营部门贷款：loans-to-private-sector
*! 货币供应量M0：money-supply-m0
*! 货币供应量M1：money-supply-m1
*! 货币供应量M2：money-supply-m2
*! 货币供应量M3：money-supply-m3
*!######## 贸易数据 ###########
*! 贸易差额：balance-of-trade
*! 资本流动：capital-flows
*! 原油产量：crude-oil-production
*! 经常账户：current-account
*! 经常账户占GDP比例：current-account-to-gdp
*! 出口：exports
*! 外债：external-debt
*! 外国直接投资：foreign-direct-investment
*! 黄金储备：gold-reserves
*! 进口：imports
*! 汇款：remittances
*! 贸易条件：terms-of-trade
*! 恐怖主义指数：terrorism-index
*! 旅游收入：tourism-revenues
*! 入境旅游人数：tourist-arrivals
*!######## GDP数据 ###########
*! GDP：gdp
*! GNP：gross-national-product
*! 不变价GDP：gdp-constant-prices
*! 农业GDP：gdp-from-agriculture
*! 建设GDP：gdp-from-construction
*! 制造业GDP：gdp-from-manufacturing
*! 矿业GDP：gdp-from-mining
*! 公共管理GDP：gdp-from-public-administration
*! 服务业GDP：gdp-from-services
*! 运输业GDP：gdp-from-transport
*! 公用事业GDP：gdp-from-utilities
*! 人均GDP：gdp-per-capita
*! PPP人均GDP：gdp-per-capita-ppp
*! 固定资本形成总额：gross-fixed-capital-formation
*!######## 政府数据 ###########
*! 庇护申请人数：asylum-applications
*! 财政支出：fiscal-expenditure
*! 政府预算值：government-budget-value
*! 政府债务：panel government-debt
*! 政府收入：government-revenues
*! 政府支出：government-spending
*!######## 住房数据 ###########
*! 建筑许可证：building-permits
*! 建筑工程产值：construction-output
*! 自置居所比率：home-ownership-rate
*! 住房指数：housing-index
*! 房屋开工率：housing-starts
*!######## 商业数据 ###########
*! 破产企业数量：bankruptcies
*! ZEW经济景气指数：zew-economic-sentiment-index
*! 小企业信心：small-business-sentiment
*! 商业信心指数：business-confidence
*! 产能利用率：capacity-utilization
*! 汽车生产：car-production
*! 车辆注册：car-registrations
*! 水泥生产：cement-production
*! 库存变化：changes-in-inventories
*! 竞争力指数：competitiveness-index
*! 竞争力排名：competitiveness-rank
*! 综合采购经理人指数：composite-pmi
*! 企业利润：corporate-profits
*! 腐败指数：corruption-index
*! 腐败排名：corruption-rank
*! 营商环境：ease-of-doing-business
*! 电力生产：electricity-production
*! 工厂订单：factory-orders
*! 互联网速度：internet-speed
*! IP地址：ip-addresses
*! 领先经济指标：leading-economic-index
*! 制造业PMI：manufacturing-pmi
*! 制造业生产：manufacturing-production
*! 新订单指数：new-orders
*! 服务业PMI：services-pmi
*! 钢铁生产：steel-production
*! 汽车总销量：total-vehicle-sales
*!######## 消费数据 ###########
*! 银行贷款利率：bank-lending-rate
*! 消费者信心指数：consumer-confidence
*! 消费信贷：consumer-credit
*! 消费支出：consumer-spending
*! 个人可支配收入：disposable-personal-income
*! 汽油价格：gasoline-prices
*! 家庭债务占国内生产总值：households-debt-to-gdp
*! 家庭债务与收入：households-debt-to-income
*! 个人储蓄：personal-savings
*! 私人部门信贷：private-sector-credit
*!######## 气候数据 ###########
*! 降水量：precipitation
*! 温度：temperature
*! 国内生产总值增长率：gdp-growth-rate
*! 贸易差额：balance-of-trade
*! 经常账户占GDP比例：current-account-to-gdp
*! 就业人数：employed-persons
*! 就业人数变化：employment-change
*! 全职工作人数：full-time-employment
*! 首次申请失业救济人数：initial-jobless-claims
*! 职位空缺：job-vacancies